DRIVER_Location = "/Users/meenakshi/PycharmProjects/chromedriver"
URL = "http://jt-dev.azurewebsites.net/#/SignUp"
CHOOSE_LANGUAGE = "#language > .ui-select-match > .btn"
SELECT_ENGLISH = "#ui-select-choices-row-1-0 .ng-binding"
ENGLISH_TEXT = "English"
SELECT_DUTCH = "#ui-select-choices-row-1-1 .ng-binding"
DUTCH_TEXT = "Dutch"
FULLNAME = "#name"
ENTER_NAME = "MeenakshiSekar"
ORGANISATION = "#orgName"
ENTER_ORG = "Meenakshi"
EMAIL = "#singUpEmail"
ENTER_EMAIL = "azurewebselenium@gmail.com"
CHECKBOX = ".ui-checkbox > .black-color.ng-binding"
BUTTON = "button"
GMAIL_URL = "https://accounts.google.com/signin/v2/identifier"
GMAIL_EMAIL = "#identifierId"
NEXT_EMAIL = "#identifierNext .VfPpkd-vQzf8d"
PWD = "input[name='password']"
ENTER_PWD = "TestPassword@@1"
PWD_NEXT = "div#passwordNext .VfPpkd-vQzf8d"
SIGNED_URL = "https://mail.google.com/mail/u/0/?tab=mm#inbox"
SIGN_IN = "Sign in"
CLICK_EMAIL = "li:nth-of-type(1) > div[role='link'] .w1I7fb"
PROMOTIONS = "td:nth-of-type(3) > div[role='tab']"
RECEIVED_EMAIL = "//div[@id=':ad']//span[@name='JabaTalks Developme.']"